# Another playbook to install Zabbix Agent on multiple Linux distributions.
# Before playing, the following variables must be put into /etc/ansible/group_vars/all:
#
# agent_major_version: x.x          # zabbix agent major version(e.g., 4.2)
# agent_version: x.x.x-x            # zabbix agent package version(e.g., 4.2.4-1)
# zabbix_server: xxx.xxx.xxx.xxx    # zabbix server ip address
#
---
- hosts: all
  tasks:
    - name: classify hosts depending on their OS family
      group_by:
        key: "{{ ansible_os_family }}_{{ ansible_distribution }}"
        parents: "{{ ansible_os_family }}"
- hosts: RedHat
  tasks:
    - name: install zabbix agent on rhel/centos 5/7
      yum:
        name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/{{ agent_major_version }}/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/zabbix-agent-{{ agent_version }}.el{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm
        state: present
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when: ansible_distribution_major_version == "5" or ansible_distribution_major_version == "7"
    - name: install zabbix agent on rhel6/centos6
      yum:
        name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/{{ agent_major_version }}/rhel/6/{{ ansible_architecture }}/zabbix-agent-{{ agent_version }}.el6.{{ ansible_machine }}.rpm
        state: present
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when: ansible_distribution_major_version == "6"
- hosts: Debian_Ubuntu
  tasks:
    - name: install zabbix agent on x86_64 ubuntu 14.04/16.04/18.04
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/{{ agent_major_version }}/ubuntu/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+{{ ansible_distribution_release }}_amd64.deb
        state: present
        force_apt_get: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_distribution_release == "trusty" or ansible_distribution_release == "xenial" or ansible_distribution_release == "bionic"
        - ansible_architecture == "x86_64"
    - name: install zabbix agent on i386 ubuntu 14.04/16.04/18.04
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/{{ agent_major_version }}/ubuntu/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+{{ ansible_distribution_release }}_i386.deb
        state: present
        force_apt_get: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_distribution_release == "trusty" or ansible_distribution_release == "xenial" or ansible_distribution_release == "bionic"
        - ansible_architecture == "i386"
- hosts: Debian_Debian
  tasks:
    - name: install zabbix agent on x86_64 debian 8/9
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/{{ agent_major_version }}/debian/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+{{ ansible_distribution_release }}_amd64.deb
        state: present
        force_apt_get: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_distribution_release == "jessie" or ansible_distribution_release == "stretch"
        - ansible_architecture == "x86_64"
    - name: install zabbix agent on i386 debian 8/9
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/{{ agent_major_version }}/debian/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+{{ ansible_distribution_release }}_i386.deb
        state: present
        force_apt_get: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_distribution_release == "jessie" or ansible_distribution_release == "stretch"
        - ansible_architecture == "i386"
- hosts: Suse_SLES
  tasks:
    - name: install zabbix agent on sles 12/15
      zypper:
        name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/{{ agent_major_version }}/sles/{{ ansible_distribution_major_version }}/x86_64/zabbix-agent-{{ agent_version }}.el{{ ansible_distribution_major_version }}.x86_64.rpm
        state: present
        disable_gpg_check: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when: ansible_distribution_major_version == "12" or ansible_distribution_major_version == "15"
  handlers:
    - name: configure zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^Server=', line: 'Server={{ zabbix_server }}' }
        - { regexp: '^ServerActive=', line: 'ServerActive={{ zabbix_server }}' }
        - { regexp: '^Hostname=', line: 'Hostname={{ ansible_hostname }}' }
    - name: restart zabbix agent service
      service:
        name: zabbix-agent
        enabled: true
        state: restarted
