---
- hosts: all
  vars:
    agent_version: 4.2.4-1
    zabbix_server: 10.10.100.131
  remote_user: root
  tasks:
    - name: install zabbix agent on x86_64 rhel5/centos5
      yum:
        name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/rhel/5/x86_64/zabbix-agent-{{ agent_version }}.el5.x86_64.rpm
        state: present
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when: 
        - ansible_facts['distribution'] == "Red Hat Enterprise" or ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "5"
        - ansible_facts['architecture'] == "x86_64"
    - name: install zabbix agent on i386 rhel5/centos5
      yum:
        name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/rhel/5/i386/zabbix-agent-{{ agent_version }}.el5.i386.rpm
        state: present
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution'] == "Red Hat Enterprise" or ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "5"
        - ansible_facts['architecture'] == "i386"
    - name: install zabbix agent on x86_64 rhel6/centos6
      yum:
        name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/rhel/6/x86_64/zabbix-agent-{{ agent_version }}.el6.x86_64.rpm
        state: present
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when: 
        - ansible_facts['distribution'] == "Red Hat Enterprise" or ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "6"
        - ansible_facts['architecture'] == "x86_64"
    - name: install zabbix agent on i386 rhel6/centos6
      yum:
        name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/rhel/6/i386/zabbix-agent-{{ agent_version }}.el6.i686.rpm
        state: present
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution'] == "Red Hat Enterprise" or ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "6"
        - ansible_facts['architecture'] == "i386"
    - name: install zabbix agent on x86_64 rhel7/centos7
      yum:
        name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/rhel/7/x86_64/zabbix-agent-{{ agent_version }}.el7.x86_64.rpm
        state: present
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution'] == "Red Hat Enterprise" or ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "7"
        - ansible_facts['architecture'] == "x86_64"
    - name: install zabbix agent on x86_64 ubuntu 14.04
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/ubuntu/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+trusty_amd64.deb
        state: present
        force_apt_get: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution_release'] == "trusty"
        - ansible_facts['architecture'] == "x86_64"
    - name: install zabbix agent on i386 ubuntu 14.04
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/ubuntu/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+trusty_i386.deb
        state: present
        force_apt_get: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution_release'] == "trusty"
        - ansible_facts['architecture'] == "i386"
    - name: install zabbix agent on x86_64 ubuntu 16.04
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/ubuntu/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+xenial_amd64.deb
        state: present
        force_apt_get: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution_release'] == "xenial"
        - ansible_facts['architecture'] == "x86_64"
    - name: install zabbix agent on i386 ubuntu 16.04
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/ubuntu/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+xenial_i386.deb
        state: present
        force_apt_get: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution_release'] == "xenial"
        - ansible_facts['architecture'] == "i386"
    - name: install zabbix agent on x86_64 ubuntu 18.04
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/ubuntu/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+bionic_amd64.deb
        state: present
        force_apt_get: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution_release'] == "bionic"
        - ansible_facts['architecture'] == "x86_64"
    - name: install zabbix agent on i386 ubuntu 18.04
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/ubuntu/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+bionic_i386.deb
        state: present
        force_apt_get: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution_release'] == "bionic"
        - ansible_facts['architecture'] == "i386"
    - name: install zabbix agent on x86_64 debian 8
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/debian/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+jessie_amd64.deb
        state: present
        force_apt_get: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution_release'] == "jessie"
        - ansible_facts['architecture'] == "x86_64"
    - name: install zabbix agent on i386 debian 8
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/debian/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+jessie_i386.deb
        state: present
        force_apt_get: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution_release'] == "jessie"
        - ansible_facts['architecture'] == "i386"
    - name: install zabbix agent on x86_64 debian 9
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/debian/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+stretch_amd64.deb
        state: present
        force_apt_get: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution_release'] == "stretch"
        - ansible_facts['architecture'] == "x86_64"
    - name: install zabbix agent on i386 debian 9
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/debian/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+stretch_i386.deb
        state: present
        force_apt_get: true
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution_release'] == "stretch"
        - ansible_facts['architecture'] == "i386"
      - name: install zabbix agent on sles 12
      zypper:
        name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/sles/12/x86_64/zabbix-agent-{{ agent_version }}.el12.x86_64.rpm
        state: present
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution'] == "SLES"
        - ansible_facts['distribution_major_version'] == '12'
      - name: install zabbix agent on sles 15
      zypper:
        name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/4.2/sles/15/x86_64/zabbix-agent-{{ agent_version }}.el15.x86_64.rpm
        state: present
      notify:
        - configure zabbix agent
        - restart zabbix agent service
      when:
        - ansible_facts['distribution'] == "SLES"
        - ansible_facts['distribution_major_version'] == '15'
  handlers:
    - name: configure zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^Server=', line: 'Server={{ zabbix_server }}' }
        - { regexp: '^ServerActive=', line: 'ServerActive={{ zabbix_server }}' }
        - { regexp: '^Hostname=', line: 'Hostname={{ ansible_hostname }}' }
    - name: restart zabbix agent service
      service:
        name: zabbix-agent
        state: restarted
