# A playbook to install Zabbix Agent on multiple Linux distributions.
---
- hosts: all
  vars:
    agent_major_version: 4.2
    agent_version: 4.2.4-1
    zabbix_server: 10.10.100.131
  remote_user: root
  tasks:
    - name: install zabbix agent on rhel/centos 5/7
      yum:
        name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/{{ agent_major_version }}/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/zabbix-agent-{{ agent_version }}.el{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm
        state: present
      notify: restart zabbix agent service
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version == "5" or ansible_distribution_major_version == "7"
    - name: install zabbix agent on rhel6/centos6
      yum:
        name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/{{ agent_major_version }}/rhel/6/{{ ansible_architecture }}/zabbix-agent-{{ agent_version }}.el6.{{ ansible_machine }}.rpm
        state: present
      notify: restart zabbix agent service
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version == "6"
    - name: install zabbix agent on x86_64 ubuntu 14.04/16.04/18.04
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/{{ agent_major_version }}/ubuntu/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+{{ ansible_distribution_release }}_amd64.deb
        state: present
        force_apt_get: true
      notify: restart zabbix agent service
      when:
        - ansible_distribution_release == "trusty" or ansible_distribution_release == "xenial" or ansible_distribution_release == "bionic"
        - ansible_architecture == "x86_64"
    - name: install zabbix agent on i386 ubuntu 14.04/16.04/18.04
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/{{ agent_major_version }}/ubuntu/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+{{ ansible_distribution_release }}_i386.deb
        state: present
        force_apt_get: true
      notify: restart zabbix agent service
      when:
        - ansible_distribution_release == "trusty" or ansible_distribution_release == "xenial" or ansible_distribution_release == "bionic"
        - ansible_architecture == "i386"
    - name: install zabbix agent on x86_64 debian 8/9
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/{{ agent_major_version }}/debian/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+{{ ansible_distribution_release }}_amd64.deb
        state: present
        force_apt_get: true
      notify: restart zabbix agent service
      when:
        - ansible_distribution_release == "jessie" or ansible_distribution_release == "stretch"
        - ansible_architecture == "x86_64"
    - name: install zabbix agent on i386 debian 8/9
      apt:
        deb: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/{{ agent_major_version }}/debian/pool/main/z/zabbix/zabbix-agent_{{ agent_version }}+{{ ansible_distribution_release }}_i386.deb
        state: present
        force_apt_get: true
      notify: restart zabbix agent service
      when:
        - ansible_distribution_release == "jessie" or ansible_distribution_release == "stretch"
        - ansible_architecture == "i386"
    - name: install zabbix agent on sles 12/15
      zypper:
        name: https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/{{ agent_major_version }}/sles/{{ ansible_distribution_major_version }}/x86_64/zabbix-agent-{{ agent_version }}.el{{ ansible_distribution_major_version }}.x86_64.rpm
        state: present
        disable_gpg_check: true
      notify: restart zabbix agent service
      when:
        - ansible_distribution == "SLES"
        - ansible_distribution_major_version == "12" or ansible_distribution_major_version == "15"
  handlers:
    - name: configure zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^Server=', line: 'Server={{ zabbix_server }}' }
        - { regexp: '^ServerActive=', line: 'ServerActive={{ zabbix_server }}' }
        - { regexp: '^Hostname=', line: 'Hostname={{ ansible_hostname }}' }
      listen: restart zabbix agent service
    - name: restart service
      service:
        name: zabbix-agent
        enabled: true
        state: restarted
      listen: restart zabbix agent service
